# yaml-language-server: $schema=https://github.com/cloudcannon/configuration-types/releases/latest/download/cloudcannon-config.latest.schema.json
collections_config:
  pages:
    path: content
    glob:
      - "_index.md"
    url: /
  posts:
    path: content/posts
    url: "/posts/[slug]/"
    _enabled_editors:
      - visual
      - content
      - data
